# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    working_directory: ~/ccibuild
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
      - run: jupyter nbconvert --to html --execute ./HW.ipynb
      - store_artifacts:
          path: ./HW.html
          destination: HW.html
